# Generated by Django 5.2.1 on 2026-06-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(max_length=100)),
                ('niveau_etude', models.CharField(max_length=100)),
                ('motivation', models.TextField()),
                ('adhesion_gratuite', models.BooleanField(default=False)),
                ('aucun_salaire', models.BooleanField(default=False)),
                ('contribution', models.BooleanField(default=False)),
                ('respect_valeurs', models.BooleanField(default=False)),
                ('developpement_communautaire', models.BooleanField(default=False)),
                ('declaration_finale', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
