# Generated by Django 5.2.1 on 2026-06-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='statut',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='ATTENTE', max_length=20),
        ),
    ]
